<?php


namespace common\components\helpers;


use yii\base\Widget;
use Yii;

class Date extends Widget
{
    public $format;
    public $value;
    private $output;

    public function init()
    {
        parent::init(); // TODO: Change the autogenerated stub

        $this->value = $this->value ? $this->value : date('Y-m-d H:i:s');

        $format = Yii::$app->formatter;

        if ($this->format) {
            $this->output = $format->asDatetime($this->value, $this->format);
        } else {
            $this->output = $format->asDatetime($this->value);
        }

    }

    public function run()
    {
        return $this->output;
    }
}